name: Build CVs

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
    types: [opened, synchronize, reopened, ready_for_review]

jobs:
  build_short:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout code"
        uses: actions/checkout@v2
      - name: "Change to adequate directory"
        run: cd ./short
      - name: "Compile LaTeX document"
        uses: hspaans/latexmk-action@v1.0.11
        with:
          format: pdf
          filename: SegarraCarlos_CV.tex
